# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1c8b5d1ee537962b77df64232a3a318d219c958e5ee98f30b6f68d1322d05b1a411adda8e1edc44d8ad2af6fbb348e964757a559fed931e95bb745a75a25f3cd

test:
  secret_key_base: 95341e946852db0f47a21a91819a70baf0270c4e5662c6d4a9fb52c4e16ac8fa051f776b712a7b48f5d3f5e280074397b2517c680592bbb79b73626091cbfbe3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
